### ISSUE TITLE
关于生成bin文件的建议

### ISSUE THREAD

**Issue by fuzqing** [webman-php/console#19]
1. 生成 `bin` 文件之后不删除 `sfx` 文件，方便下次生成的时候不用再次下载，提高生成速度，还能节省下载服务器的带宽
2. 是否可以在下载的时候先检查一下本地目录是否存在 `sfx` 文件，存在的时候再检测一下本地版本是否与服务器版本一致，不一致再下载

**Comment by walkor** [comment]
你说这两点是需要的，如果你愿意的话可以帮忙优化下。
还有phar打包时如何排除掉build目录

**Comment by fuzqing** [comment]
排除某个目录需要提供一个 `pattern`  类似这样子 `'#^(?!.*(build))(.*)$#'`
这部分配置在 `app.php` 里面，不过被注释了，目前内置的正则默认不打包 `test` ，`.git` 之类的目录。
可以在文档中写一下，做个提示（如果提供了正则，那么需要自己在正则中排除 `build` 目录），方便让那些需要排除部分文件或目录的用户自己写对应的正则，然后在代码中判断是否提供了正则表达式，如果没有提供，就默认排除 `build` 目录就行，其它都打包进去。

**Comment by fuzqing** [comment]
代码类似于这样子
![image](https://user-images.githubusercontent.com/15156836/220012492-bd7985b7-c65b-4501-aae3-e1a33115fadf.png)

**Comment by walkor** [comment]
好的，非常感谢
