### ISSUE TITLE
webman/event 冲突

### ISSUE THREAD

**Issue by Joycezhangw** [webman-php/console#33]
使用 `webman/event` 插件，需要将该插件的配置： `config/plugin/event` 目录 copy 到主目录 `config` 目录下，才可以使用 `event 事件`。
但是：`config/plugin/event/app.php` 目录配置跟 `config/plugin/event/console/app.php` 冲突，无法使用命令`php webman app-plugin:create trade` 创建插件应用

**Comment by walkor** [comment]
源码里并没有这个文件 `config/plugin/event/console/app.php`

**Comment by Joycezhangw** [comment]
> 源码里并没有这个文件 `config/plugin/event/console/app.php`

我在安装后，在根目录下的 `config` 会生成`config/plugin/webman/console/app.php` 这个文件

**Comment by walkor** [comment]
重新创建个webman项目试下吧，没有人反馈过这个问题，源码里也没有这个文件



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Joyce Zhang ***@***.***&gt;
发送时间: 2024年4月6日 12:01
收件人: webman-php/console ***@***.***&gt;
抄送: walkor ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [webman-php/console] webman/event 冲突 (Issue #33)





  
源码里并没有这个文件 config/plugin/event/console/app.php
  
我在安装后，在根目录下的 config 会生成config/plugin/webman/console/app.php 这个文件
