### ISSUE TITLE
php8.4环境下报错  

### ISSUE THREAD

**Issue by 18827676454** [webman-php/console#36]
相关代码
![image](https://github.com/user-attachments/assets/5e6685bc-809f-4417-a0a1-29d791ec1bf9)

PS D:\project\webman> php webman version
PHP Fatal error:  Uncaught ErrorException: Webman\Console\Commands\BuildPharCommand::__construct(): Implicitly marking parameter $name as nullable is deprecated, the explicit nullable type must be used instead in D:\project\webman\vendor\webman\console\src\Commands\BuildPharCommand.php:18

**Comment by walkor** [comment]
php 8.4刚出不久，很多composer库不支持，建议不要现在用php8.4
